export interface CityInfo {
  city: string;
  country: string;
  continent: string;
}

export const CONTINENT_NAME_MAP: Record<string, string> = {
  'continent-europe': '유럽 (Europe)',
  'continent-asia-pacific': '아시아-태평양 (Asia-Pacific)',
  'continent-north-america': '북미 (North America)',
  'continent-south-america': '남미 (South America)',
  'continent-africa': '아프리카 (Africa)',
};

export const CITY_CODE_MAP: Record<string, CityInfo> = {
  AKL: { city: '오클랜드 (Auckland)', country: '뉴질랜드 (New Zealand)', continent: '아시아-태평양 (Asia-Pacific)' },
  AMS: { city: '암스테르담 (Amsterdam)', country: '네덜란드 (Netherlands)', continent: '유럽 (Europe)' },
  ANA: { city: '애너하임 (Anaheim)', country: '미국 (United States)', continent: '북미 (North America)' },
  ATL: { city: '애틀랜타 (Atlanta)', country: '미국 (United States)', continent: '북미 (North America)' },
  AUH: { city: '아부다비 (Abu Dhabi)', country: '아랍에미리트 (UAE)', continent: '아시아-태평양 (Asia-Pacific)' },
  BCN: { city: '바르셀로나 (Barcelona)', country: '스페인 (Spain)', continent: '유럽 (Europe)' },
  BDX: { city: '보르도 (Bordeaux)', country: '프랑스 (France)', continent: '유럽 (Europe)' },
  BIR: { city: '버밍엄 (Birmingham)', country: '영국 (United Kingdom)', continent: '유럽 (Europe)' },
  BKK: { city: '방콕 (Bangkok)', country: '태국 (Thailand)', continent: '아시아-태평양 (Asia-Pacific)' },
  BLB: { city: '빌바오 (Bilbao)', country: '스페인 (Spain)', continent: '유럽 (Europe)' },
  BLR: { city: '벵갈루루 (Bengaluru)', country: '인도 (India)', continent: '아시아-태평양 (Asia-Pacific)' },
  BNA: { city: '내슈빌 (Nashville)', country: '미국 (United States)', continent: '북미 (North America)' },
  BNE: { city: '브리즈번 (Brisbane)', country: '호주 (Australia)', continent: '아시아-태평양 (Asia-Pacific)' },
  BOM: { city: '뭄바이 (Mumbai)', country: '인도 (India)', continent: '아시아-태평양 (Asia-Pacific)' },
  BOS: { city: '보스턴 (Boston)', country: '미국 (United States)', continent: '북미 (North America)' },
  BRI: { city: '브라이턴 (Brighton)', country: '영국 (United Kingdom)', continent: '유럽 (Europe)' },
  BSL: { city: '바젤 (Basel)', country: '스위스 (Switzerland)', continent: '유럽 (Europe)' },
  BUD: { city: '부다페스트 (Budapest)', country: '헝가리 (Hungary)', continent: '유럽 (Europe)' },
  BUE: { city: '부에노스아이레스 (Buenos Aires)', country: '아르헨티나 (Argentina)', continent: '남미 (South America)' },
  CAN: { city: '광저우 (Guangzhou)', country: '중국 (China)', continent: '아시아-태평양 (Asia-Pacific)' },
  CGN: { city: '쾰른 (Cologne)', country: '독일 (Germany)', continent: '유럽 (Europe)' },
  CHI: { city: '시카고 (Chicago)', country: '미국 (United States)', continent: '북미 (North America)' },
  CPH: { city: '코펜하겐 (Copenhagen)', country: '덴마크 (Denmark)', continent: '유럽 (Europe)' },
  CPT: { city: '케이프타운 (Cape Town)', country: '남아프리카공화국 (South Africa)', continent: '아프리카 (Africa)' },
  CUN: { city: '칸쿤 (Cancún)', country: '멕시코 (Mexico)', continent: '북미 (North America)' },
  CWL: { city: '카디프 (Cardiff)', country: '영국 (United Kingdom)', continent: '유럽 (Europe)' },
  DAL: { city: '댈러스 (Dallas)', country: '미국 (United States)', continent: '북미 (North America)' },
  DEN: { city: '덴버 (Denver)', country: '미국 (United States)', continent: '북미 (North America)' },
  DUB: { city: '더블린 (Dublin)', country: '아일랜드 (Ireland)', continent: '유럽 (Europe)' },
  DUS: { city: '뒤셀도르프 (Düsseldorf)', country: '독일 (Germany)', continent: '유럽 (Europe)' },
  DXB: { city: '두바이 (Dubai)', country: '아랍에미리트 (UAE)', continent: '아시아-태평양 (Asia-Pacific)' },
  EGY: { city: '카이로 (Cairo)', country: '이집트 (Egypt)', continent: '아프리카 (Africa)' },
  FRA: { city: '프랑크푸르트 (Frankfurt)', country: '독일 (Germany)', continent: '유럽 (Europe)' },
  GDL: { city: '과달라하라 (Guadalajara)', country: '멕시코 (Mexico)', continent: '북미 (North America)' },
  GDN: { city: '그단스크 (Gdańsk)', country: '폴란드 (Poland)', continent: '유럽 (Europe)' },
  GLA: { city: '글래스고 (Glasgow)', country: '영국 (United Kingdom)', continent: '유럽 (Europe)' },
  GNT: { city: '헨트 (Ghent)', country: '벨기에 (Belgium)', continent: '유럽 (Europe)' },
  GUJ: { city: '구자라트 (Gujarat)', country: '인도 (India)', continent: '아시아-태평양 (Asia-Pacific)' },
  GVA: { city: '제네바 (Geneva)', country: '스위스 (Switzerland)', continent: '유럽 (Europe)' },
  HAM: { city: '함부르크 (Hamburg)', country: '독일 (Germany)', continent: '유럽 (Europe)' },
  HEL: { city: '헬싱키 (Helsinki)', country: '핀란드 (Finland)', continent: '유럽 (Europe)' },
  HKG: { city: '홍콩 (Hong Kong)', country: '홍콩 (Hong Kong)', continent: '아시아-태평양 (Asia-Pacific)' },
  HOU: { city: '휴스턴 (Houston)', country: '미국 (United States)', continent: '북미 (North America)' },
  ICN: { city: '인천 송도 (Incheon)', country: '대한민국 (South Korea)', continent: '아시아-태평양 (Asia-Pacific)' },
  JHB: { city: '요하네스버그 (Johannesburg)', country: '남아프리카공화국 (South Africa)', continent: '아프리카 (Africa)' },
  KAR: { city: '카를스루에 (Karlsruhe)', country: '독일 (Germany)', continent: '유럽 (Europe)' },
  KRK: { city: '크라쿠프 (Kraków)', country: '폴란드 (Poland)', continent: '유럽 (Europe)' },
  KTW: { city: '카토비체 (Katowice)', country: '폴란드 (Poland)', continent: '유럽 (Europe)' },
  KUL: { city: '쿠알라룸푸르 (Kuala Lumpur)', country: '말레이시아 (Malaysia)', continent: '아시아-태평양 (Asia-Pacific)' },
  LAS: { city: '라스베이거스 (Las Vegas)', country: '미국 (United States)', continent: '북미 (North America)' },
  LON: { city: '런던 (London)', country: '영국 (United Kingdom)', continent: '유럽 (Europe)' },
  LYS: { city: '리옹 (Lyon)', country: '프랑스 (France)', continent: '유럽 (Europe)' },
  MAA: { city: '마스트리흐트 (Maastricht)', country: '네덜란드 (Netherlands)', continent: '유럽 (Europe)' },
  MAD: { city: '마드리드 (Madrid)', country: '스페인 (Spain)', continent: '유럽 (Europe)' },
  MAN: { city: '맨체스터 (Manchester)', country: '영국 (United Kingdom)', continent: '유럽 (Europe)' },
  MEC: { city: '메카 (Mecca)', country: '사우디아라비아 (Saudi Arabia)', continent: '아시아-태평양 (Asia-Pacific)' },
  MEL: { city: '멜버른 (Melbourne)', country: '호주 (Australia)', continent: '아시아-태평양 (Asia-Pacific)' },
  MEX: { city: '멕시코시티 (Mexico City)', country: '멕시코 (Mexico)', continent: '북미 (North America)' },
  MIA: { city: '마이애미 (Miami)', country: '미국 (United States)', continent: '북미 (North America)' },
  MIL: { city: '밀라노 (Milan)', country: '이탈리아 (Italy)', continent: '유럽 (Europe)' },
  MLG: { city: '말라가 (Málaga)', country: '스페인 (Spain)', continent: '유럽 (Europe)' },
  MTY: { city: '몬테레이 (Monterrey)', country: '멕시코 (Mexico)', continent: '북미 (North America)' },
  NCE: { city: '니스 (Nice)', country: '프랑스 (France)', continent: '유럽 (Europe)' },
  NDA: { city: '노이다 (Noida)', country: '인도 (India)', continent: '아시아-태평양 (Asia-Pacific)' },
  NGO: { city: '나고야 (Nagoya)', country: '일본 (Japan)', continent: '아시아-태평양 (Asia-Pacific)' },
  NYC: { city: '뉴욕 (New York)', country: '미국 (United States)', continent: '북미 (North America)' },
  OSA: { city: '오사카 (Osaka)', country: '일본 (Japan)', continent: '아시아-태평양 (Asia-Pacific)' },
  OSL: { city: '오슬로 (Oslo)', country: '노르웨이 (Norway)', continent: '유럽 (Europe)' },
  PAR: { city: '파리 (Paris)', country: '프랑스 (France)', continent: '유럽 (Europe)' },
  PDX: { city: '포틀랜드 (Portland)', country: '미국 (United States)', continent: '북미 (North America)' },
  PHX: { city: '피닉스 (Phoenix)', country: '미국 (United States)', continent: '북미 (North America)' },
  PZN: { city: '포즈난 (Poznań)', country: '폴란드 (Poland)', continent: '유럽 (Europe)' },
  RIM: { city: '리미니 (Rimini)', country: '이탈리아 (Italy)', continent: '유럽 (Europe)' },
  RIO: { city: '리우데자네이루 (Rio de Janeiro)', country: '브라질 (Brazil)', continent: '남미 (South America)' },
  RIX: { city: '리가 (Riga)', country: '라트비아 (Latvia)', continent: '유럽 (Europe)' },
  ROM: { city: '로마 (Rome)', country: '이탈리아 (Italy)', continent: '유럽 (Europe)' },
  ROT: { city: '로테르담 (Rotterdam)', country: '네덜란드 (Netherlands)', continent: '유럽 (Europe)' },
  SAN: { city: '샌디에이고 (San Diego)', country: '미국 (United States)', continent: '북미 (North America)' },
  SEL: { city: '서울 (Seoul)', country: '대한민국 (South Korea)', continent: '아시아-태평양 (Asia-Pacific)' },
  SGP: { city: '싱가포르 (Singapore)', country: '싱가포르 (Singapore)', continent: '아시아-태평양 (Asia-Pacific)' },
  SHA: { city: '상하이 (Shanghai)', country: '중국 (China)', continent: '아시아-태평양 (Asia-Pacific)' },
  SLC: { city: '솔트레이크시티 (Salt Lake City)', country: '미국 (United States)', continent: '북미 (North America)' },
  SPO: { city: '상파울루 (São Paulo)', country: '브라질 (Brazil)', continent: '남미 (South America)' },
  STO: { city: '스톡홀름 (Stockholm)', country: '스웨덴 (Sweden)', continent: '유럽 (Europe)' },
  SYX: { city: '싼야 (Sanya)', country: '중국 (China)', continent: '아시아-태평양 (Asia-Pacific)' },
  TLS: { city: '툴루즈 (Toulouse)', country: '프랑스 (France)', continent: '유럽 (Europe)' },
  TPA: { city: '탬파 (Tampa)', country: '미국 (United States)', continent: '북미 (North America)' },
  TPE: { city: '타이베이 (Taipei)', country: '대만 (Taiwan)', continent: '아시아-태평양 (Asia-Pacific)' },
  UTR: { city: '위트레흐트 (Utrecht)', country: '네덜란드 (Netherlands)', continent: '유럽 (Europe)' },
  VER: { city: '베로나 (Verona)', country: '이탈리아 (Italy)', continent: '유럽 (Europe)' },
  VIE: { city: '빈 (Vienna)', country: '오스트리아 (Austria)', continent: '유럽 (Europe)' },
  VLC: { city: '발렌시아 (Valencia)', country: '스페인 (Spain)', continent: '유럽 (Europe)' },
  WAW: { city: '바르샤바 (Warsaw)', country: '폴란드 (Poland)', continent: '유럽 (Europe)' },
  YOW: { city: '오타와 (Ottawa)', country: '캐나다 (Canada)', continent: '북미 (North America)' },
  YVR: { city: '밴쿠버 (Vancouver)', country: '캐나다 (Canada)', continent: '북미 (North America)' },
  YYZ: { city: '토론토 (Toronto)', country: '캐나다 (Canada)', continent: '북미 (North America)' },
};

export function resolveCityInfo(cityCode: string, fallbackContinentClass?: string): CityInfo {
  const code = (cityCode || '').toUpperCase().trim();
  if (CITY_CODE_MAP[code]) {
    return CITY_CODE_MAP[code];
  }
  const fallbackContinent = fallbackContinentClass ? CONTINENT_NAME_MAP[fallbackContinentClass] || '기타 (Other)' : '기타 (Other)';
  return {
    city: code || '알 수 없음',
    country: '기타 (Other)',
    continent: fallbackContinent,
  };
}
